[pytest]
minversion = 6.0
addopts = -ra -q --cov=app --cov-report=term-missing --cov-fail-under=90
testpaths =
    test
    app

[coverage:run]
source = app
branch = True

[coverage:report]
fail_under = 90
show_missing = True
skip_covered = True
exclude_lines =
    pragma: no cover
    if TYPE_CHECKING:
    @overload
    ...
