from .analyzer import analyzer_router
from .apikey import apikey_router
from .auth import auth_router
# from .brlogin import brlogin_router
from .broker_auth import broker_router
from .chartink import chartink_router
from .core import core_router
from .dashboard import dashboard_router
from .latency import latency_router
from .log import log_router
from .master_contract_status import master_contract_status_router
from .orders import orders_router
from .pnltracker import pnltracker_router
from .python_strategy import python_strategy_router
from .sandbox import sandbox_router
from .search import search_router
from .security import security_router
from .settings import settings_router
from .strategy import strategy_router
from .telegram import telegram_router
from .traffic import traffic_router
from .tv_json import tv_json_router
from .websocket import websocket_router
